#!/bin/bash
#set -x
DEPLOY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ADDON_PATH="$( dirname "$DEPLOY_DIR" )"
#echo "$ADDON_PATH"
#exit 0

#ITSI_PARENT_FOLDER_NAME="_itsi"
#ITSI_SRC_BASE_PATH="$DEPLOY_DIR/$ITSI_PARENT_FOLDER_NAME"
#ITSI_TEMP_BASE_PATH="$TEMP_DIR/$ITSI_PARENT_FOLDER_NAME"
#mkdir "$ITSI_TEMP_BASE_PATH"
#ITSI_VOLUME_OPTIONS=""
#if [ -d "$ITSI_SRC_BASE_PATH" ]; then
#  for APP_NAME in $ITSI_SRC_BASE_PATH/*/
#  do
#      APP_NAME="${APP_NAME%*/}"
#      APP_NAME="${APP_NAME##*/}"
#      ITSI_TEMP_APP_PATH="$ITSI_TEMP_BASE_PATH/$APP_NAME"
#      cp -r $ITSI_SRC_BASE_PATH/$APP_NAME $ITSI_TEMP_BASE_PATH > /dev/null 2>&1
#      ITSI_VOLUME_OPTIONS="$ITSI_VOLUME_OPTIONS -v $ITSI_TEMP_APP_PATH:/opt/splunk/etc/apps/$APP_NAME:ro"
#  done
#fi

NETWORK_NAME="workato-integration-test"
docker network create $NETWORK_NAME > /dev/null 2>&1
docker rm -fv workato_splunk > /dev/null 2>&1

CONTAINER_ID=$(docker run -d -p 8081:8000 -p 8082:8089 --name workato_splunk --network $NETWORK_NAME -e "SPLUNK_START_ARGS=--accept-license" -e "SPLUNK_CMD=edit user admin -password admin -auth admin:changeme" -e "WORKATO_INTEGRATION_TEST=1" -v $ADDON_PATH:/opt/splunk/etc/apps/workato_addon_for_splunk:rw -v $ADDON_PATH/deploy/test_app:/opt/splunk/etc/apps/test_app:rw splunk/splunk:latest)

docker rm -fv workato_test > /dev/null 2>&1
docker run --name workato_test --network $NETWORK_NAME -it --rm -v $ADDON_PATH/deploy/test:/usr/src/myapp:ro -w /usr/src/myapp python:2.7 python2.7 integration_test.py workato_splunk 8089 workato_test

read -p "Done! Press [Enter] to cleanup..."

docker rm -fv "$CONTAINER_ID" > /dev/null 2>&1
docker network rm "$NETWORK_NAME" > /dev/null 2>&1
sudo chown $USER -R ../
